version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_webserver
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=jsrNd6Ca4wKlFM_LM36Fj3cS4FNlPmp_V2oqRMkAjDLtzAOSYChlxHr_PsVHXIzg5bntnuNsZoZzdwYJBjJshw==
      - INFLUXD_HTTP_ALLOW_ORIGIN=*
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "influx", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  influxdb_data:
  influxdb_config:

networks:
  backend_network:
    driver: bridge

